name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
[[kv_namespaces]]
binding = "KV"
id = "68076ad217104f649066df6f0c6b9f1f"
#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id
